### ISSUE TITLE
Add letsencrypt

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#1]
Add SSL certificates using [letsencrypt](http://letsencrypt.org/) to haproxy (or move to e.g. nginx).
Require SSL for all connections (except, perhaps, for verifying certificate requests).

**Comment by wvengen** [comment]
Recent trick I saw for first-time setup of certificate (when the config won't load because the certificates aren't present yet): put full certificate config in webserver configuration (referencing `/etc/letsencrypt/live/${FQDN}/{fullchain,privkey}.pem`), don't start the webserver yet and run `certbot --standalone -d "${FQDN}"` to obtain the certificate (supply extra options to avoid interactive prompts). Then start the webserver, now that the certificates are there.

It's probably a good idea to put the certificates on a docker volume.

**Comment by kidhab** [comment]
With LE's webroot plugin one can obtain a new certificate over port 80 and without stopping the webserver.

**Comment by wvengen** [comment]
@kidhab yes, but then we'd need to start the server first without ssl (because there are no certs and it won't start), and then with. Could also generate dummy certs first (maybe letsencrypt allows that for verification), or find an option to allow starting the server without ssl (even if it's in the config), or to add ssl config after obtaining certificates. Whatever works best.

**Comment by wvengen** [comment]
[haproxy-letsencrypt](https://hub.docker.com/r/bringnow/haproxy-letsencrypt/) may be useful

**Comment by wvengen** [comment]
* [acme.sh](https://github.com/Neilpang/acme.sh) - tiny letsencrypt impl, with [daemon mode and docker](https://github.com/Neilpang/acme.sh/wiki/Run-acme.sh-in-docker)
* [haproxy-acme-validation-plugin](https://github.com/janeczku/haproxy-acme-validation-plugin/) - haproxy plugin for acme validation, and a [docker sample](https://github.com/bringnow/docker-haproxy-letsencrypt)
* Greenhost's [letsencrypt setup](https://github.com/greenhost/certbot-haproxy) based on haproxy

Most implementations I've found seem to suggest cron for renewal, and after the cronjob haproxy is restarted. That is not an issue for us. I've seen people [suggest](https://github.com/docker/dockercloud-haproxy/issues/87) to mount the docker socket in the letsencrypt container, but I'd rather not.

I'd go for either a haproxy-integrated solution, where both cert renewal and haproxy restart are taken care of. Still, a cronjob is a different container, so I don't see how haproxy can be restarted without moving complexity into the haproxy process.

So I'd go for the other option, which is to have a container doing all certbot stuff, where haproxy forwards the relevant validation urls, and a shared volume with certificates. The haproxy needs to reload when the certificate file changes (haproxy's reloads are cheap, no or little connection loss).
And, hooray, that gives some hits: [haproxy with inotify](https://github.com/million12/docker-haproxy) as done [here](https://github.com/million12/docker-haproxy/blob/master/container-files/bootstrap.sh#L64), and [some hints](https://serverfault.com/a/734105).

**Comment by paroga** [comment]
I run certbot per cronjob in a separate container. Unfortunately I did not setup the haproxy reload yet, since I do regular restarts at the moment anyway. I'd like to share as much as possible with the Austrian setup, but I did not have the time to extract the code from my setup. When do you need the SSL configuration? @wvengen I've added you to a private repository, with the current setup, which still contains some sensitive information.

**Comment by wvengen** [comment]
Thanks, that's useful in many ways (and I'll be careful).
I've actually managed to get auto-reload working using inotify (#16).

**Comment by wvengen** [comment]
I do like your certbot setup, by the way.

**Comment by paroga** [comment]
i'd prefere to use `certbot` since it's the "offical" ACME client

for reload you only need to send `SIGUSR2` to the haproxy container: `docker kill --signal=USR2 foodcoopsnet_haproxy_1` if you mount the docker socket you can do that also within a container (which is running e.g. certbot)

**Comment by wvengen** [comment]
I would be careful mounting the docker socket in there (as indeed has been suggested in docker haproxy's issues), doesn't that give full access to managing containers and such?

**Comment by paroga** [comment]
yes it does. AFAIK there is no fine granted access control system for it, so it's not a perfekt solution, but IMHO it's cleaner than having multiple processes in one container, which is simply not the way how you should use Docker

**Comment by wvengen** [comment]
Hmmm, no ideal world.
Ideally, perhaps, haproxy could watch its own files and directories for restarts. With that missing, I would still opt for something that gracefully restarts haproxy - which needs a parent process because of the way haproxy manages graceful restarts.
I have seen several instances of docker projects that use supervisor processes. And what I read is that [_Each container should only have one concern_](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/) is more about having one function than one process.
