### ISSUE TITLE
Figure out how to share costs

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#10]
The new foodcoops.net infrastructure needs a small amount of money each month for the server. Domain name costs. Perhaps other expenses.

How will we, as a group of food cooperatives, pay this together?
It has been suggested that this could be arranged by donations. I think it's wise if someone thinks of how this could be given shape. Suggested keywords: communication, community, sustainable.

It has also been [suggested](http://foodsoft.51229.x6.nabble.com/Notes-call-today-tp1415p1429.html) that we keep track of notes and financial transactions in a "global" Foodsoft instance. (As in "eat your own dogfood".)

**Comment by robwa** [comment]
Who would be willing to open a (private) bank account for that? If we had one, we could manage that with our "global" Foodsoft instance. Then we could ask people to send money to that account.

TODOs might be:
- [x] open bank account (sense.lab)
- [x] list the expected costs (see below)
- [x] ask people for donations (see #19)

**Comment by 1resu** [comment]
My two cents:

I think it would be more trustful if the bank account belongs to an organisation. Also with the advantage that such an organisation can give our sponsors an official receipt for their donations.

Maybe I can ask a local non-profit organisation if they want to provider their account for our project...

**Comment by wvengen** [comment]
Thanks for your comments, @1resu. I think an organisation account would be a good idea. Maybe the organisation you're thinking of. I think there are also organisations who want to support open source projects, e.g. [Software Freedom Conservancy](https://sfconservancy.org/), or [dyne.org](http://dyne.org/) (I've had good contact with the last before).

**Comment by robwa** [comment]
If we ask an existing organisation, this organisation would have to rent the server as well. Or we would have to issue invoices.

In the first case, the liability is rather on the organisation side. But maybe that's not a problem, because we never run into trouble. :)

**Comment by wvengen** [comment]
That would be preferable, yes. If not, the organisation could reimburse server rental by one of us.
Software Freedom Conservancy explicitely [mentions](https://sfconservancy.org/about/) this as part of its activities - though they focus on developing software, not hosting it.

Just came across [this article on European FOSS umbrella organisations](https://lwn.net/Articles/713073/).

**Comment by wvengen** [comment]
It looks like both [Commons Conservancy](https://commonsconservancy.org/) (NL) and [Center for the Cultivation of Technology](https://techcultivation.org/) (DE) could be a good fit. I'd be happy to contact the former to check if this might at all be a match. What do you think?

**Comment by robwa** [comment]
so we have some options

* Commons Conservancy (NL) (@wvengen would contact them)
* Center for the Cultivation of Technology (DE) (@robwa would contact them)
* @1resu, which one did you mean?

**Comment by robwa** [comment]
> Center for the Cultivation of Technology (DE)

I talked to them. Our project would meet what they'd like to offer. But as they are just building new structures, they can't support us right now.

We can meet them in Berlin or at 34C3 in Leipzig.

If we are still looking for a solution in January 2018, we can talk to them again.

**Comment by JuliusR** [comment]
What if we just start with a simple intermediate solution and keep this as an issue assigned to one of us?

If anyone agrees to do the long-term job (finding a suitable organization, perform a later transition) then I offer to create a bank account and rent some commercial server providing my personal name. That way, we could proceed with the overdue transition from the old infrastructure while the assigned person would have to ensure that we do not get stuck with that intermediate solution.

I would also welcome anyone else to provide his name for bank account and server, of course.

**Comment by kidhab** [comment]
I can ask the people from [Sense.Lab](https://senselab.org) if they want to "host" this project. They are part of the foodcoop in Rostock and also published a [book](https://food-coop-einstieg.de) about how to setup a new foodcoop. I think this would fit nicely.

**Comment by robwa** [comment]
Listing expected costs (per year):
* Server: 60 € (up to 108 €)
* Domain: 14-18 € (e.g. [domainprovider.de](https://www.domainprovider.de/preisliste.php), netcup, ...)

Total: About 75 € up to 130 € per year (or simply around **100 €**).

Am I missing something?

**Comment by wvengen** [comment]
I wouldn't mind doing a small yearly donation to organizations who help us, like Systemausfall (mailing lists), Sense.Lab (if that turns out well).

**Comment by kidhab** [comment]
Today we got a positive vote from Sense.Lab: they would like to be the organisation for all official parts of this project. As I'm also part of Sense.Lab I think we can communicate easily in all matters.

**Comment by wvengen** [comment]
That's great! \o/

**Comment by robwa** [comment]
From my point of view this is done and we can go on with #19.
