### ISSUE TITLE
Figure out user support

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#11]
Where there are users, there are questions. Where there is software, there are bugs. We need to figure out how to handle that, so that both the community and foodcoops.net team know what to expect.

The operations team would certainly be involved when technical issues arise. Downtime, bugs, certain questions ("where did my apple go - or was the click lost?"). Can we find volunteers for first-line support (some groups indicated that they'd be willing to contribute by doing something), or will we setup a forum where everyone can help each other (would that need someone to look after)? Or something else?

Maybe this is too much organisation, and we can just start and see where it goes. That's also fine. But let's be clear about it and communicate so.

**Comment by wvengen** [comment]
One little part may be a status page, where users can see if everything is working as expected. [Statuspage](https://www.statuspage.io/) has free plans for open source projects. (For this aspect, I'm happy using an external service provider, as it does not expose user data, is public data already, and it works also when our systems are having trouble.)

**Comment by robwa** [comment]
A forum might be nice, but we had to maintain another part of software.

If we stay with email communication, we could have two mailing lists:
* info/mail/support/crew list with people willing to help (public access)
* moderated members list, that we can use for information (e.g. donation calls, see #10)

**Comment by 1resu** [comment]
Let's clarify which kind of users needs to be supported. I don't think that a regular member of a single foodcoop will aks for support. Instead I think that every foodcoop has someone who is responsible for tech stuff. For this kind of persons a mailing list would do the job (and we have fewer maintance to do).

We can create a mailing list with our local tech collective. We only have to choose a name, e.g. foosoft-support@...

**Comment by robwa** [comment]
I think `foodsoft-support@...` is fine. All tech interested or responsible members of any coop can be on the list. And we can still open it for public submission (e.g. via `info@foodcoops` or `support@foodcoops`) so that anyone can get in contact with us.

In my opinion we need a second list `foodsoft-announce@...` which might have more subscribers and which only ourselves will be allowed to post on. We send mails to that list if there are maintenance shutdowns or if we need donations.

**Comment by robwa** [comment]
@1resu, would you mind creating one or two lists?

Who has existing mail addresses of foodcoops and other users?

**Comment by kidhab** [comment]
We can use the mailing list service of systemausfall.org. If you're ok with it I will ask for two lists.

**Comment by wvengen** [comment]
Sounds good! Maybe it's good to have distinction between the software (_foodsoft_) and the hosting (_foodcoops(.net)_) namewise (and there is also a group of people which may also be _foodcoops_).
Anyway, I propose that we use `foodcoops-support@` for the hosting platform. `foodsoft-*@` lists then still live on nabble (or wherever), which are for discussing the software (and can be open).

**Comment by robwa** [comment]
One of the first lists we will need is the one where we ask for donations. Which one will it be? `foodcoops-announce`?

**Comment by robwa** [comment]
We now have the two suggested lists.

Who has addresses to put on the *announce* list, which we will use for asking for donations soon?

We can start writing a text for the first mailing. Any suggestions?

**Comment by wvengen** [comment]
@before and me have the email addresses of people who mailed to transition@foodcoops.nl, I think this would be useful for the _announce_ list (I imagine this could be a public list, for anyone interested)

**Comment by wvengen** [comment]
The lists are created, thanks @robwa.
http://foodsoft.51229.x6.nabble.com/Lists-for-announcements-and-support-td1468.html
Because the email addresses were gone in the above message (spam measures), they are:
* `foodcoops-support` at `lists.systemausfall.org` ([subscribe](https://systemausfall.org/admin/list-subscribe?list_address=foodcoops-support@lists.systemausfall.org))
* `foodcoops-announce` at `lists.systemausfall.org` ([subscribe](https://systemausfall.org/admin/list-subscribe?list_address=foodcoops-announce@lists.systemausfall.org))

**Comment by robwa** [comment]
I think we can close this and go on with #19.

**Comment by wvengen** [comment]
:+1:
It may be good to have a followup issue when the support team becomes clear, to organize that, and make expectations clear on support, both for the support team and the foodcoops.

**Comment by wvengen** [comment]
In the last [call](http://foodsoft.51229.x6.nabble.com/Call-tonight-tp1504p1508.html), @paroga voiced the concern that there was no mail archive accessible to all members on systemausfall lists.

Nabble has a feature where it can [function](http://n8.nabble.com/archive-your-mailing-list.html) as a mailing-list archive, I think that works for now (though we shouldn't use that link, better within the foodsoft namespace already existing). Then we can interact with users without the need for them to subscribe, and have an archive (closed, so that only the support team can read it).

Another thing: let's use support@foodcoops.info as contact address, and forward that to the systemausfall support list. This provides an easily recognizable contact address, and allows us to redirect it when needed. Later we may move to @foodcoops.net when that is transferred.

(Re-opening issue until the archive is setup.)

**Comment by wvengen** [comment]
It appears there are mail archive options at systemausfall :)
Nevertheless, to keep things in one place, I've also setup Nabble archives for these lists ([support](http://foodsoft.51229.x6.nabble.com/foodsoft-global-support-f1510.html) and [announce](http://foodsoft.51229.x6.nabble.com/foodsoft-global-announce-f1511.html)), for now accessible to the global-ops group in Nabble.

Let's wait what Sense.Lab says about publishing their bank account number whether we open the announce list as publically readable archive, or not.
