### ISSUE TITLE
Make sending email work

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#12]
Foodsoft sends mail messages, so we need a way to send them properly.
Add an email server docker instance that acts as a relay for Foodsoft. This email server can then either forward it to an upstream server, or just deliver it by itself (in which case we'll need to setup some anti-spam measures like SPF and such).
It would be useful to keep #2 in mind, where we'll also need to route incoming mail (see also links there).
Multiple domains as well as wildcard email addresses (but not catch-all, I guess) will be necessary.

**Comment by kidhab** [comment]
I'm not familar with docker right now but I like to setup postfix. So I self assign me to this task.

**Comment by wvengen** [comment]
There's a good starting point in https://github.com/foodcoops/foodcoops.net/pull/17/commits/561cd12fe504a447d9e1ca64f6ebeb98ec734611 (PR #17) (albeit with a lot more than this issue is strictly about). Hope this helps to get started.

**Comment by wvengen** [comment]
Is this getting anywhere?
As a first step, we could set the smtp server details in env variables in the Rails apps. But in the end I'd prefer to have a front-end postfix who does the routing.

**Comment by wvengen** [comment]
We can use Sense.Lab's SMTP, for details see [mailing list post](http://foodsoft.51229.x6.nabble.com/Updates-after-contacting-Sense-Lab-tp1513p1519.html).

**Comment by wvengen** [comment]
It would still be nice to have postfix in between. Is someone working on that, or shall we close the issue and leave it for #2?

**Comment by wvengen** [comment]
Let's leave adding postfix for #2 then.

**Comment by wvengen** [comment]
We're having too many TLS connections- http://foodsoft.51229.x6.nabble.com/email-problems-tp1674.html

**Comment by kidhab** [comment]
Hi,

Am Fri, 02 Mar 2018 02:22:59 -0800
schrieb wvengen <notifications@github.com>:

> We're having too many TLS connections -
> http://foodsoft.51229.x6.nabble.com/email-problems-tp1674.html

The server's IP address (46.38.240.91) is now exlcuded from Postfix
rate limiting. I suppose that this solves this error.

steffen

**Comment by wvengen** [comment]
Thanks, that's great! :+1:

**Comment by kidhab** [comment]
I discoverd another limit of the postfix server (`Recipient address rejected: Rate limit reach, retry later `)  -  if a specified number of mails per day were exceeded postfix refused to deliver new mails.

I exluded the foodsoft server's IP address from this limit.
