### ISSUE TITLE
Write first mail to users

### ISSUE THREAD

**Issue by robwa** [foodcoops/foodcoops.net#19]
We need to write our first post to the *announce* list. Contents might be:
* State who we are, what we are doing and why one is on the list.
* Explain how to leave the list.
* Write down a short timetable/ road map.
* List the expected yearly costs.
* Ask for donations.
* Ask for needed suppliers (#4)
* Indicate future support address and ask people to join support team.

Depends on #10 and #11.

**Comment by arouel** [comment]
I will take over this task. Some question from my side:
* Shall we write an email beforehand even when not everything is clear so far because a lot of time passed since summer?
* What "list" do you mean and how to leave it?
* Looks like we have also a dependency around the timetable or roadmap, right?

**Comment by robwa** [comment]
> Shall we write an email beforehand even when not everything is clear so far because a lot of time passed since summer?

I think, we don't have to write something beforehand. If everything works well, sense.lab will decide on friday, if they support us. If yes, we can close #10 and write this email next week.



> What "list" do you mean and how to leave it?

I meant the announce list of #11.



> Looks like we have also a dependency around the timetable or roadmap, right?

Yes. Maybe we can just create a simple timetable/ roadmap when working on this ticket?

**Comment by arouel** [comment]
Sounds reasonable. Thank you for the feedback.

**Comment by wvengen** [comment]
I would love to ask for foodcoops details to compile a list and put it on the website (#22). Would this be a moment to ask about that info, or maybe later?

**Comment by kidhab** [comment]
I think all current foodsoft users are informated about the transmission of the setup to our new project. So it's fine to write them now.

**Comment by arouel** [comment]
@wvengen agreed, we can ask within the first email if they are fine to be mentioned on a public list. Or shall we make it to a requirement?

**Comment by wvengen** [comment]
@before great. We could make it opt-out instead, don't want to force it on groups (e.g. some might not want new members out of the blue, or stay under the radar for other reasons).

**Comment by robwa** [comment]
This is done, isn't it?
