### ISSUE TITLE
Add email router

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#2]
With different instances receiving email (Foodsoft for message replies, different instances, plus sharedlists for article updates), there is need for a router to direct incoming email to the correct application. This can be done by adding a [Postfix](http://www.postfix.org/) instance. Can also do outbound email. See e.g. [docker-postfix](https://github.com/hokstadconsulting/docker-postfix) for an example. It is important that wildcards matching addresses like `foodsoft-1.a918cd@foodcoops.net` can also be routed.

**Comment by wvengen** [comment]
If sensible, I guess we prefer to use the [mailu postfix](https://hub.docker.com/r/mailu/postfix/) image, because that's what paroga already uses elsewhere (and we'd like to keep it aligned). Seems like a good base image too. We just need to strip out parts we don't use: we only use forwarding outgoing mails to the upstream smtp server (though being able to deliver like a regular mta would be nice to keep), and forwarding incoming mails to the appropriate service. So no local accounts or storing mail.

**Comment by wvengen** [comment]
http://www.postfix.org/VIRTUAL_README.html
https://ubuntuforums.org/showthread.php?t=1690948
https://www.howtoforge.com/community/threads/postfix-relay-one-domain-to-smarthost-a-all-else-to-smarthost-b.62955/

for relaying out (not needed right now):
https://anothersysadmin.wordpress.com/2009/02/06/postfix-as-relay-to-a-smtp-requiring-authentication/

**Comment by wvengen** [comment]
This is working now.
Pending: adding `MAILER_PREFIX` (and `MAILER_DOMAIN`?) to Foodsoft, for mail replies.

**Comment by wvengen** [comment]
When `MAILER_PREFIX` is implemented in Foodsoft, we need to revert https://github.com/foodcoops/foodcoops.net/commit/c35edeadc580dd9866a6ba16b8d560790e8b7fb2.

**Comment by kidhab** [comment]
I think the initial idea was to let postfix decide where to route incoming reply mail based on the [domain](https://github.com/foodcoops/foodsoft/blob/master/config/app_config.yml.SAMPLE#L130).

**Comment by wvengen** [comment]
Yes. In some cases one would want to share the domain between several apps (and/or use regular email addresses).
Sharedlists has an option for the using `MAILER_PREFIX`, which is prepended to the mail address (and stripped on processing). Also, when only one domain is required for a whole setup, it's easier to set it up (one less domain to configure), so I think it's a good idea to implement this eventually.

**Comment by kidhab** [comment]
> Also, when only one domain is required for a whole setup, it's easier to set it up (one less domain to configure), so I think it's a good idea to implement this eventually.

I dont' disagree with you. As as side note: It's already possible to route incoming mails for sharedlists and foodsoft using the same mail domain. With postfix you have to setup a transport map like this (assuming `MAILER_PREFIX=scharedlists+`):
```
/^sharedlists\+[0-9]*\.([0-9A-Z])*@foodcoops\.net$/    smtp:[1.2.3.4]:2525
/^(.*)\.[0-9\.]*\.[A-Z0-9]*@foodcoops\.net$/           smtp:[1.2.3.4]:2526
```
Based on how [sharedlists](https://github.com/foodcoops/sharedlists/blob/master/lib/tasks/mail.rake#L38) and [foodsoft](https://github.com/foodcoops/foodsoft/blob/master/plugins/messages/app/mailers/messages_mailer.rb#L9) build the mail address.

**Comment by wvengen** [comment]
The second regex is a little generic, but would already work. I'd be for using that for now, thanks!

**Comment by kidhab** [comment]
Replies by email are working now.
