### ISSUE TITLE
Status/uptime page

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#20]
To help users (and ourselves) know when there are problems, it would be useful to have a status page. [Statuspage](https://www.statuspage.io/) would be one option, and is free for open source projects (at least, they used to - I'd be happy to check).

My preference would be to use an external service for this, because it's the one thing that needs to be up when all else is failing.

(Continued from https://github.com/foodcoops/foodcoops.net/issues/11#issuecomment-328298321)

**Comment by wvengen** [comment]
The people from statuspage were so kind to give us a free plan. But that still needs monitoring for automated status updates (supports pingdom / new relic / datadog / librato - the have an agent on the server, which I'd like to avoid). Up/down monitoring works with email too.
Other monitoring services would be [statuscake](https://pages.statuscake.com/), [serviceuptime](http://www.serviceuptime.com/), [uptimerobot](https://uptimerobot.com/), [insping](https://www.insping.com/), [uptimedoctor](http://www.uptimedoctor.com/), [binarycanary](https://www.binarycanary.com/). Many also provide a basic status page (with varying quality).

**Comment by wvengen** [comment]
And from pingdom we have a (single user) plan with 10 monitors, that should be enough.
Inlog email: `dev-voko-statuspage@willem.engen.nl` (can become `@foodcoops.net` after transition).

**Comment by wvengen** [comment]
Added Foodsoft and Sharedlists on http://stats.pingdom.com/97m58vhnf1fv
will add SMTP server later, when we've set that up, as well as the foodcoop-adam instance.

**Comment by wvengen** [comment]
It may be nice to add a check for upstream SMTP, making email troubleshooting easier.
Does anyone object to putting the SMTP username and password (https://github.com/foodcoops/foodcoops.net/issues/12#issuecomment-341891861) in a pingdom test? @JuliusR

**Comment by JuliusR** [comment]
> It may be nice to add a check for upstream SMTP, making email troubleshooting easier.
> Does anyone object to putting the SMTP username and password (https://github.com/foodcoops/foodcoops.net/issues/12#issuecomment-341891861) in a pingdom test? 

@kidhab or @robwa, any objections?

**Comment by robwa** [comment]
@kidhab?

**Comment by wvengen** [comment]
I plan to add the check some time soon now.
