### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#21]
Update [foodcoops.github.io](https://foodcoops.github.io/) with the new situation.

* Mention global foodcoops group of people (that's us)
* Add to hosting options and demo
* Explain how to participate
  - get an instance (incl. what info is needed)
  - how and why donations
  - helping out
  - support
* Finances
* Partners
  - Sense.Lab
  - Systemausfall
  - ?

**Comment by kidhab** [comment]
I'll write some information about Sense.Lab and systemausfall.org

**Comment by wvengen** [comment]
Started this on branch [feature/global-foodcoops](https://github.com/foodcoops/foodcoops.github.io/tree/feature/global-foodcoops).

**Comment by wvengen** [comment]
Regarding support, we [talked about](http://foodsoft.51229.x6.nabble.com/Call-tonight-tp1504p1508.html) giving clarity about functional support (how do I use Foodsoft), which is what the foodsoft-discuss@ mailing-list it is for, and technical support (there is a malfunction, I'd like to move my instance to a subdomain, etc.), for which there is an email address.

Regarding different languages, for support@ address a person in the team who speaks the language of the email will respond. For the foodsoft-discuss@ mailing list, it would be useful to have several for different languages, but English is still the preferred language.

Also explain all of this in a support section.

**Comment by wvengen** [comment]
I've published an initial version, comments welcome.

**Comment by robwa** [comment]
I really like the page!

In the global section on the general hosting page the contact mail address `foodsoft-support` is not existing. Should it read `foodcoops-...`?

**Comment by wvengen** [comment]
Thanks! I'll change it. ~~Also I'll point the button to the support section instead of an email address (so that people can make a choice between mailing list and support email).~~

**Comment by wvengen** [comment]
Now that app.foodcoops.net has moved, I did a last check on the website content, and I consider this done.
