### ISSUE TITLE
Add foodsoft:latest instance as preview

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#26]
Just an idea: add a Foodsoft instance for the `latest` docker tag. This allows people to try out upcoming Foodsoft features, and make testing before a release easier.
On update, one would need to run database migrations as well (or drop and recreate from seed).
There would only be a demo foodcoop (no multicoops needed).

**Comment by arouel** [comment]
I really like this idea. Doing the database migration would be good to catch earlier possible regressions.

**Comment by wvengen** [comment]
This is live now, but the assets don't include the sub-path and can't be found as a result. That's something to fix. It should be possible to set a variable like `RAILS_RELATIVE_URL_ROOT` (but references from within assets won't work, those need a recompilation of the assets, unfortunately).

**Comment by wvengen** [comment]
Hmmm, `RAILS_RELATIVE_URL_ROOT` is not enough, now getting a routing error on foodsoft latest:

> ActionController::RoutingError (No route matches [GET] "/latest/assets/application-76712f722c3b9dd09c89bc8e9ec5bb412dba517dab145a6fd5d1da70d51888f4.js")

**Comment by wvengen** [comment]
Maybe we can add a symlink [like here](https://gist.github.com/ebeigarts/5450422#capistrano).

**Comment by wvengen** [comment]
Ok, need [this](https://gist.github.com/ebeigarts/5450422#rails), added to Foodsoft.

**Comment by wvengen** [comment]
When the docker image is ready and deployed, this will be accessible via:
https://app.foodcoops.net/latest/demo

For translations, access
https://app.foodcoops.net/latest/demo?locale=ach
