### ISSUE TITLE
WARNING: Connection pool is full, discarding connection: localhost

### ISSUE THREAD

**Issue by vasyugan** [foodcoops/foodcoops.net#27]
Not sure what to make of this warning, but I guess if a connection with localhost goes wrong, we are in trouble.

Does this mean that the container cannot work if some other application uses port 443? 

userland proxy: listen **tcp 0.0.0.0:443: bind: address already in use**

root@ida:/home/jr/foodsoft/foodcoops.net# docker-compose up -d
Creating network "foodcoopsnet_default" with the default driver
Creating foodcoopsnet_sharedlists_cron_1
Creating foodcoopsnet_mariadb_1
Creating foodcoopsnet_foodsoft_cron_1
Creating foodcoopsnet_foodsoft_worker_1
Creating foodcoopsnet_haproxy_1
Creating foodcoopsnet_sharedlists_1
Creating foodcoopsnet_phpmyadmin_1
Creating foodcoopsnet_certbot_1
Creating foodcoopsnet_redis_1
Creating foodcoopsnet_foodsoft_1
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost
WARNING: Connection pool is full, discarding connection: localhost

aaaand here is the result:

ERROR: for haproxy  Cannot start service haproxy: driver failed programming external connectivity on endpoint foodcoopsnet_haproxy_1 (f10c1fa8f5d2a14e1a3e29d5f0b711c34ec0684a28a3a926d7787279cd8bce80): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
root@ida:/home/jr/foodsoft/foodcoops.net#

**Comment by wvengen** [comment]
Yes, if you are already using port 443 for something else, then you shouldn't let docker bind to it.

**Comment by wvengen** [comment]
Hint: see [haproxy's port section in `docker-compose.yml`](https://github.com/foodcoops/foodcoops.net/blob/master/docker-compose.yml#L47).
