### ISSUE TITLE
Notification mails do not work (including the feedback form)

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#35]
You can reproduce the problem by following the "feedback" link (top right corner): If you fill some text and submit the form then an "internal server error" is shown. Ironically, that error page claims to report the issue (which fails, of course).

The reason seems to be here:

> ```
> An error occurred when sending a notification using 'email' notifier. ArgumentError: SMTP To address may not be blank: []
> ```

**Comment by wvengen** [comment]
Ouch, that is weird. It should be picked up from the environment variables. Maybe the notifier doesn't recognise it?

**Comment by wvengen** [comment]
We need to set the environment variables `EMAIL_SENDER` and `ERROR_RECIPIENTS` in `.env`.

**Comment by wvengen** [comment]
Indeed the 'feedback' is sent to the error recipients (wasn't aware of that before).

**Comment by JuliusR** [comment]
I suggest to create a confidential mailing list with an archive, and use that as the recipient.

**Comment by wvengen** [comment]
And perhaps the feedback address would better go to the support list. That would need a small change in Foodsoft.

**Comment by JuliusR** [comment]
We can reuse an existing sympa installation in order to create a sympa instance for a subdomain of our choice. We could create as many public or private mailing lists with archive. I suggest to setup a sympa instance for `lists.foodcoops.net` and create the error-notification list there. Say `reports-foodsoft@lists.foodcoops.net`. @wvengen, do you like that idea?

Separate recipient lists (error reports vs. user feedback) sounds good to me.

**Comment by wvengen** [comment]
I'd also be for a different mailing-list solution than Nabble, provided it is a) not run on the app.foodcoops.net server (communication is especially important when we have technical issues), and b) we have trust that the archive is expected to be available for 10+ years (it is an important resource that needs to be available - even longer than the foodcoops.net initiative would exist).

For error notifications and feedback, I wouldn't have these requirements (but it's nice not to have too many different mailing list solutions we're using).

**Comment by JuliusR** [comment]
> it is a) not run on the app.foodcoops.net server (communication is especially important when we have technical issues)

Right. By using `lists.foodcoops.net` we obviously need a working DNS setup, but I am fine with that.

> b) we have trust that the archive is expected to be available for 10+ years (it is an important resource that needs to be available - even longer than the foodcoops.net initiative would exist).

Predicting 10+ years is hard. What we can do is regularly backup the messages. We could then have a shutdown plan for how to handle the data (erase the data to be erased and archive the data to be archived). As an archive, we can generate static html pages which can be kept available with low cost and little effort. By using our own domain, it is in our hands to keep alive what deserves to survive.

**Comment by 1resu** [comment]
Some thoughts:

- The current Sympa server runs on an idependet server. It would not be affected from downtimes of netcup.
- As we are in control of the foodcoops.net domain we can setup every DNS record that we want to.
- There are no plans to shutdown Sympa the next decade.
- I also thought about the subdomain thing: if there are no plans to use foodcoops.net for real mail accounts we can use it as root domain for all lists addresses.

**Comment by wvengen** [comment]
- using an existing Sympa service sounds good to me (some downtime would be acceptable to me, as long as it doesn't coincide/correlate with `app.foodcoops.net` downtime)
- if we have a shutdown plan, that should be fine (or use existing archive like [MARC](https://marc.info/) or [mail archive](https://www.mail-archive.com/))
- I'd be for `lists.foodcoops.net`, which is clear and has flexibility for the future

**Comment by JuliusR** [comment]
I just created a confidential mailing list with archive. Please contact me such that I can add you as co-owners of that list.

> We need to set the environment variables `EMAIL_SENDER` and `ERROR_RECIPIENTS` in `.env`.

This is the next step. I will try that soon.

**Comment by JuliusR** [comment]
> We need to set the environment variables `EMAIL_SENDER` and `ERROR_RECIPIENTS` in `.env`.

Setting `ERROR_RECIPIENTS` was enough since `EMAIL_SENDER` has a proper default: https://github.com/foodcoops/foodcoops.net/blob/e19793cdf3c4c541b4bd95e869d46bb67ef97851/docker-compose.yml#L23

**Comment by JuliusR** [comment]
I have successully tested the feedback form. However, I am still the only subscriber and mailing-list admin. I do not dare to blindly add your email address, so please allow me to add your email address to the new mailing list.

**Comment by kidhab** [comment]
Closing this issue as we have a working setup for notification mails.
