### ISSUE TITLE
Cant setup database following the setup documentation

### ISSUE THREAD

**Issue by milesthedisch** [foodcoops/foodcoops.net#37]
After building the docker file and following steps in the docs, I seem to be getting errors when executing the rake:db commands.

The errors are permission errors saying `foodsoft@%` does not have permission.

Is there something I'm doing wrong?

Cheers

**Comment by JuliusR** [comment]
Unfortunately, the `README.md` is not perfectly up to date. Recently I tried to follow the instructions. With [these fixes](https://github.com/JuliusR/foodcoops.net/commit/d1fe50371bad5e445ec5ee4f15a428ec42b3a46d) I was able to arrive at a minimal setup. I did not find the time to clean it up.

Does that help? If you find some time then feel free to improve the instructions.

**Comment by milesthedisch** [comment]
Hey JuliusR that got me through the setup thanks for the help! And also for getting back to me so quickly.
