### ISSUE TITLE
Cleanup unused images

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#38]
`docker system df` claims that we can reclaim more than 30 GB by cleaning up unused images. It should be safe to run `docker image prune` while all containers are up.

I do not feel confident enough to perform the image cleanup on our production system. Who can do it?

**Comment by wvengen** [comment]
Good one.
Maybe we need to prune automatically after updating too.

**Comment by JuliusR** [comment]
I just performed a manual cleanup. Root partition usage has been reduced from 45 GiB to 18 GiB.

The system survived for several years without automatic cleanup. I think that automatic pruning is not worth the hassle. Feel free to open a new issue if you disagree.
