### ISSUE TITLE
management of contact information and announcements

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#42]
When new foodcoops join and when contact persons change, I am used to update `/root/foodcoop-contacts.txt`.

What is our workflow for keeping the [announcement list](https://wat.systemausfall.org/info/foodcoops-announce) up-to-date? Here is my favorite solution:

We discard `foodcoop-contacts.txt` and manage contact information with the [foodcoops-announce mailing list on systemausfall](https://wat.systemausfall.org/info/foodcoops-announce). Consequently, we make all contact persons to be subscribed to that list, and they must not (un)subscribe on their own. If non-contact persons are interested in announcements, they can still subscribe for the [nabble mirror](http://foodsoft.51229.x6.nabble.com/foodsoft-global-announce-f1511.html).

What are your thoughts on this?

**Comment by kidhab** [comment]
I created a new list foodcoops-announce@lists.foodcoops.net and added all address from the contacts file to it.

We should clarify on every new foodsoft request that we'll use the contact addresses for this list.

**Comment by kidhab** [comment]
I added a note at our [Terms of service](https://github.com/foodcoops/foodcoops.github.io/blob/master/tos.md) about the usage of the contact addresses.
