### ISSUE TITLE
repair and simplify initial setup

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#44]
The [setup instructions](https://github.com/foodcoops/foodcoops.net/blob/2d3b48852318463a99ee99dee17acfc6e81c8907/README.md#setup) currently do not work. See #40 for an attempt to fix that.

In addition, I would prefer a non-interactive setup (currently, one needs to enter the mysql root password twice). As a bonus, I suggest to generate safe random passwords (`openssl rand -base64 32` or [`pwgen -1 32`](https://github.com/docker-library/mariadb/blob/58bef417cbeea4eb6b15c46b6097c3cbb99beb32/10.5/docker-entrypoint.sh#L227)) by default. What do you think?

**Comment by JuliusR** [comment]
Let us make it work in #40, and discuss further steps here.

### Requirements (ongoing edit)

#### simplicity

What I (@JuliusR) like about the current interactive setup is the low level of abstraction: You can explicitly see what is going on because you type (or paste) everything yourself. However, I really like the idea of a one-step setup.

* single fully automated script sets up everything "from scratch" (let us assume a good™ linux with docker and docker-compose installed)
* script should be simple and obvious to follow
* script should be easy to customize

#### good error behavior

If anything fails unexpectedly:
- immediately stop
- provide a useful error message
- support some kind of retry (possibly erasing the incomplete configuration)

#### protection against dataloss due to accidental re-setup
- it should be hard to erase an existing configuration/database

**Comment by JuliusR** [comment]
The very first database initialization could be done with `/docker-entrypoint-initdb.d`, see https://hub.docker.com/_/mariadb/ . I believe that is better than initialization via database client because it is free of race conditions [1]. I need to figure out if we can easily inject the configured passwords into `/docker-entrypoint-initdb.d`.

[1] The problematic order I have in mind is:
1. database container started
2. database-initialization attempt from client
3. database server ready to accept connections

EDIT: The [waiting script from this blog post](https://cweiske.de/tagebuch/docker-mysql-available.htm) also looks promising.

**Comment by JuliusR** [comment]
see #45 for a first attempt (WIP, but should work already)

**Comment by JuliusR** [comment]
There has been some progress in #45, and I am looking forward to your feedback.

**Comment by kidhab** [comment]
Closing this issue because we don't use Docker for app.foodcoops.net anymore.
