### ISSUE TITLE
inconsistent use of charset and collation

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#46]
There is a mix of charsets and collations used in the production database: Although most `foodsoft_???` databases are using a default setting of `utf8mb4_unicode_520_ci`, they are containing columns with `utf8_unicode_ci` and `utf8_general_ci`. See https://github.com/foodcoops/foodsoft/issues/798#issuecomment-756063540.

Should we do anything about that?

**Comment by kidhab** [comment]
All databases, tables and columns use `utf8mb4_unicode_520_ci` as collation now.
