### ISSUE TITLE
support email has admin user in some instances

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#48]
The default admin user still exists in 4 instances. See https://github.com/foodcoops/foodcoops.net/issues/36#issuecomment-549354470. For new foodcoops, I documented the current practice in #47.

The old admin users can be found with the following command:
```
FoodsoftConfig.foodcoops.each{|fc| FoodsoftConfig.select_foodcoop(fc); User.all.where(email: 'SUPPORT_EMAIL_ADDRESS_INSERTED_HERE').each{|u| puts fc } }
```
I suggest to contact those 4 foodcoops: We can announce that we will delete those user accounts a few weeks from now.

Any objections?

**Comment by kidhab** [comment]
It seems that the default admin is actually a member of one of the foodcoops. I deactivated the default admin in all other three instances. Hence it's no longer possible to login with this mail address.
