### ISSUE TITLE
canonical homepage domain

### ISSUE THREAD

**Issue by JuliusR** [foodcoops/foodcoops.net#49]
Currently, the homepage has two domains:

https://foodcoops.github.io/
https://foodcoops.net/

with

> ` <link rel="canonical" href="https://foodcoops.github.io/">`

Should we clarify this by forwarding (301) one of them to the other? My clear preference is `foodcoops.net` because we "own" that one.

**Comment by JuliusR** [comment]
Also see @paroga's BTW here: https://github.com/foodcoops/foodcoops.net/issues/36#issuecomment-549354470.

**Comment by wvengen** [comment]
Yes, let's use foodcoops.net.

**Comment by JuliusR** [comment]
I just realized that https://www.foodcoops.net/ goes through our [reverse proxy](https://github.com/foodcoops/foodcoops.net/blob/2d3b48852318463a99ee99dee17acfc6e81c8907/haproxy/haproxy.cfg#L32). I suggest that we reconfigure the DNS: The main page should be independent of our app server. I think that has already been suggested here: https://github.com/foodcoops/foodcoops.net/issues/36#issuecomment-549354470. I just did not understand yet. I will care about this.

BTW: What about the rDNS entry of our app server? Currently it is set to `v22017115078354939 [DOT] powersrv [DOT] de`. I suggest to set `app.foodcoops.net` there. Any objections?

**Comment by wvengen** [comment]
Good idea, it's better that the website is reachable when the server isn't.
Updating reverse DNS would be a god idea too, yes.

**Comment by 1resu** [comment]
I just updated the DNS records.
We can update die rerverse record with the server adminitration panel of our provider.

**Comment by JuliusR** [comment]
HTTPS is broken because `js` and `css` links are using absolute URLs with HTTP. The URLs are created, e.g., [here](/foodcoops/foodcoops.github.io/blob/9d26137ba975ce9b941d78a204160ebfa6406742/_includes/head.html#L17) with `absolute_url`. According to [this page](https://talk.jekyllrb.com/t/absolute-url-rendering-links-as-http-localhost/3293), `absolute_url` produces HTTP in dev mode and HTTPS in production mode.

However, I suggest to just replace `absolute_url` by `relative_url` where that makes sense. Do you see any reasons not to prefer `relative_url`?

**Comment by wvengen** [comment]
Our design is derived from [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/). It might be solved in upstream (but maybe not) and I think that is quite some more work than changing `absolute_url` to `relative_url`. I'd go for your suggestion.

**Comment by JuliusR** [comment]
I will give it a try using `relative_url`.

**Comment by JuliusR** [comment]
> I will give it a try using `relative_url`.

I stopped that change mid-way because there are some cases that are hot handled correctly with `relative_url`: canonical link, RSS feeds, social-media stuff.

**Comment by JuliusR** [comment]
Instead, I changed the `url` config: https://github.com/foodcoops/foodcoops.github.io/commit/141225b341599eb9e59f5a6001689c6d5dc38a45 . That commit changed the css and js urls to start with `https://www.foodcoops.net/assets/...`.

However, our certificate is active for `https://foodcoops.net` only. As a temporary fix, I removed the www prefix in https://github.com/foodcoops/foodcoops.github.io/commit/1b8e92ef414415fb180f892b57221e633dffc13c . Now everything looks good to me.

I like the shorter url, and I suggest to use `https://foodcoops.net` from now on. Any objections?

**Comment by wvengen** [comment]
Thanks, @JuliusR!
I _think_ we could use `relative_url` for the js asset, since that was the only thing that broke, iirc.
Do we want to enforce https? In that case it doesn't matter.

`https;//foodcoops.net/` sounds good to me :) The only downside is that you can't use a `CNAME`, but Github Pages provides IP addresses so that should be ok (just need to remember to update them when they mail us that the IPs change - which I don't expect to happen, or maybe once or twice in the site's lifetime).

**Comment by JuliusR** [comment]
I just set the rDNS of our app server to `app.foodcoops.net`. Updating is said to take up to 48 hours.
