### ISSUE TITLE
Describe deployment and update workflow

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#5]
We've settled on Docker images and docker-compose for deployment.
Now how will we deploy this, and how will updates happen? (Preferably without downtime.) Both of Foodsoft, sharedlists and services like MySQL, Redis and Postfix. How will configuration updates happen? How are old image versions being cleaned up?
This needs to be figured out and documented, so that the whole team can do this. Some discussion on the mailing list would be useful so that everyone is on board.

**Comment by wvengen** [comment]
We're now using [docker-compose](https://docs.docker.com/compose/) for describing the whole stack. There are some environment variables (with things like secret keys) to set up (can be put in `.env`, for example), and we'll need a way to deploy configuration changes. This could be updating the files, then running `docker-compose build && docker-compose up -d`, which would take care of re-building the local docker adaptions and updating the running images. May incur a little downtime during container restart, which I think is acceptable for us.

We could have a git repository on the server, with a post-commit [hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that runs `docker-compose`. Prior art in e.g. [compose-hook](https://github.com/wader/compose-hook), a [blog post](https://tridnguyen.com/articles/simple-heroku-like-workflow-with-git-and-docker-compose/), [deploying a bot](https://aranair.github.io/posts/2017/01/21/how-i-deployed-golang-bot-on-digital-ocean/). While these examples use the `post-receive` hook, I'd put at least the build step in an `update` hook, because it's useful to see if there are errors occuring or not, and have git reject the update if a build error happens.

We could even auto-update on Github push, either with Travis CI (it supports [docker-compose](https://docs.travis-ci.com/user/docker/) - we could even test the build), or a webhook that we listen to on the server. Perhaps leave this for later, a manual push is fine to start with.

(It _is_ possible to keep the git repository within docker, but that brings a chicken and egg problem.)

**Comment by paroga** [comment]
One additional problem with just running it as ha post-commit hook is, that it won't trigger on security updates in a base container.

Did you check out what Docker Cloud could do for us?

**Comment by wvengen** [comment]
Good point.
Docker Cloud has a dedicated docker [agent](https://docs.docker.com/docker-cloud/infrastructure/byoh/) (replacing the `docker` binary) that controls the instances from the cloud service. I think this is a bit invasive, and it seems to require a credit card, besides.
I did see no option to trigger something after a docker build :(

We can add a [build hook](https://docs.docker.com/docker-cloud/builds/advanced/).
We could also run a cronjob every now and then to check for updates.
Or build docker images on Travis and deploy them there (like [this](https://www.linux.com/learn/automatically-deploy-build-images-travis)).

I'm not too familiar with how Docker Cloud handles (security) updates of base images. Do they trigger rebuilds of all depending images, or do we need to detect this and trigger a rebuild?

(sidenote: [doker-bench-security](https://github.com/docker/docker-bench-security) may be good to look at some time)

**Comment by wvengen** [comment]
There is a [stackoverflow question](https://stackoverflow.com/questions/26423515/how-to-automatically-update-your-docker-containers-if-base-images-are-updated) on rebuilding images when base image is updated, plus some interesting answers. One of them mentions that [repository links](https://docs.docker.com/docker-hub/builds/#repository-links) will do this. I've set these up where they were missing.

**Comment by wvengen** [comment]
Proposed setup:
* Run cronjob every night to apply base image updates
* Git repository
  * with post-receive hook to build
  * with update hook to run updated images
  * separate user with access to docker and docker-compose (but otherwise locked down)
  * setup authorize_keys for team (related to #8)
* Document
  * initial deployment (incl. database setup)
  * deployment of updates
  * how to revert an update
  * adding a foodcoop (incl. database)
  * adding a member to the team (nabble, Github, server access) (part of #8)

I think this would be a good first step, later we could see if we want auto-deploy or not.

**Comment by wvengen** [comment]
An example setup:

```sh
REMOTE=/tmp/testrepo.git
WORKTREE=/tmp/testrepo

DO=echo # for debugging

mkdir $WORKTREE
git init --bare $REMOTE
GIT_DIR=$REMOTE git config advice.detachedHead false

cat >$REMOTE/hooks/update <<HOOK
#!/bin/sh

if [ "\$1" != "refs/heads/master" ]; then
  echo "Please push to the master branch only" 1>&2
  exit 1
fi

if [ ! -e $WORKTREE/.env ]; then
  echo "Please put your configuration in $WORKTREE/.env" 1>&2
  exit 1
fi

GIT_WORK_TREE=$WORKTREE git checkout --force \$3 &&
cd $WORKTREE &&
$DO docker-compose build --pull --force-rm
HOOK
chmod a+x $REMOTE/hooks/update

cat >$REMOTE/hooks/post-receive <<HOOK
#!/bin/sh

cd $WORKTREE &&
$DO docker-compose up -d
HOOK
chmod a+x $REMOTE/hooks/post-receive
```

Thanks to [githooks](https://git-scm.com/docs/githooks) and [git-website-howto](http://toroid.org/git-website-howto).

**Comment by wvengen** [comment]
Now that the approach as done on the production machine is different, the documentation needs to be changed. Feel free to remove the setup-git-script.

**Comment by wvengen** [comment]
If I may assign, you @paroga, as you setup the current deployment.

**Comment by paroga** [comment]
my current script is in the `master` branch. I just want an agreement on the basic process before I start documenting it 😉
