### ISSUE TITLE
Foodsoft deployment with only upstream SMTP configuration?

### ISSUE THREAD

**Issue by decentral1se** [foodcoops/foodcoops.net#51]
Hi, I'm struggling to understand if it is possible to configure Foodsoft with only an upstream SMTP mail configuration and still retain both incoming and outgoing mail functionality?

It seems like the `smtp` container ([source](https://github.com/foodcoops/foodcoops.net/blob/master/docker-compose.yml#L120)) contains a postfix configuration which is mandatory for incoming mail functionality?

Or another way, is it possible to run Foodsoft, use mail functionality but not run your own mail server?

Sorry if this is the wrong place to raise the issue but I'm a bit lost as to where is the right place.

**Comment by decentral1se** [comment]
Got it working.

**Comment by kidhab** [comment]
It would be nice to add that information to the documentation. Can you describe your steps as a comment to this issue or as a PR? Thanks.
