### ISSUE TITLE
Where is Redis in the Ansible setup?

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#55]
@kidhab I'm not seeing any installation or setup of Redis, even though it is used by Foodsoft. Especially when closing orders, this becomes relevant (with all the background jobs). Does this still needs to be added, or am I missing something?

**Comment by wvengen** [comment]
Hmm, closing orders does work in https://app.foodcoops.net/demo/

**Comment by kidhab** [comment]
There is a Foodsoft [role](https://github.com/foodcoops/foodcoops.net/tree/master/Ansible/roles/foodsoft) in the Ansible folder. it runs the following tasks:

- [Installation](https://github.com/foodcoops/foodcoops.net/blob/master/Ansible/roles/foodsoft/tasks/packages.yml#L15) of redis
- [Setting](https://github.com/foodcoops/foodcoops.net/blob/master/Ansible/roles/foodsoft/templates/systemd/foodsoft.conf.j2#L5) the environment variable with a systemd settings file
- Using this variable in all [cron jobs](https://github.com/foodcoops/foodcoops.net/blob/master/Ansible/roles/foodsoft/tasks/cron.yml#L15)

**Comment by wvengen** [comment]
Somehow I expected this as a separate role.
But I see. It didn't occur to me that installing `redis` would also make it run by default. Sure thing!

Thanks for explaining so well!
