### ISSUE TITLE
Publish sharedlists on docker hub

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#6]
For #3, we'll need sharedlists to be published on docker hub.

**Comment by wvengen** [comment]
Since we don't have access to the foodsoft organization on Docker Hub (I hope we [will get it](https://forums.docker.com/t/how-know-who-own-a-organization/27274/4) and can move back, but who knows how long that will take), I've created the [foodcoopsnet](https://hub.docker.com/u/foodcoopsnet/) organization. Here we can publish sharedlists for the time being.

**Comment by wvengen** [comment]
@paroga what do you think, does it make sense to move foodsoft to the foodcoopsnet org on Docker Hub, so that we can specify which branches/tags/etc to build, can see logs, and have full control? (Until we get access to the foodcoops account, but I doubt if that will ever work out ...)

**Comment by paroga** [comment]
sorry, i though i added you already to the foodcoops organization. i've done it now, so you could move sharedlists to the existing organization

**Comment by wvengen** [comment]
Ah, that's great, thanks!!
