### ISSUE TITLE
Ask Dutch suppliers to send updates to new addresses

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#7]
Before the Dutch foodcoops can move, [sharedlists](https://github.com/foodcoops/sharedlists) needs to get updates from [De Nieuwe Band](https://nieuweband.nl/) and [Bioromeo](http://www.bioromeo.nl/). They need to send the updates to the new mail address (per supplier).

As an intermediate solution, the existing single mail address can be forwarded to both new address. Sharedlists' mail-from + subject filter will stop the mails from the wrong supplier. Only temporarily, please.

Depends on #2 and #3.

**Comment by wvengen** [comment]
I've forwarded the addresses I'm receiving the article lists on, to the approriate @app.foodcoops.net addresses. Seems to work! After a couple of weeks, supposing it keeps working smoothly, I'll ask them to use the new addresses directly (to cut dependence on my mail routing).

**Comment by wvengen** [comment]
Seems to work with forwards, all shared suppliers were updated on the 3rd of april.

**Comment by wvengen** [comment]
I updated Odin manually some time ago, it seems they either aren't sending updates anymore. Sent a mail to request that.

**Comment by wvengen** [comment]
Odin added our email (through a forward), Wed 19 Jan we hope to see an update.

**Comment by wvengen** [comment]
We get them, but it seems we don't support the zip-format (in which the xml is present) yet.

**Comment by kidhab** [comment]
I think we can use [Rubyzip](https://github.com/rubyzip/rubyzip) to read the zip file's content into memory and import it.

**Comment by wvengen** [comment]
Yes. And because the files can be quite large, it's best to do it streaming. I've done something related before [in this gist](https://gist.github.com/wvengen/3a93e1f55d5d412b1d1b197150550edd) with gzip, but it seems that Rubyzip supports [streaming directly](https://www.rubydoc.info/github/rubyzip/rubyzip/Zip%2FFile%2Eopen_buffer). Let's see :)

**Comment by wvengen** [comment]
Addressed in https://github.com/foodcoops/sharedlists/issues/30.

**Comment by kidhab** [comment]
Closing this issue:
- Odin import works now.
- De Nieuwe Band was apparently closed.
- And Bio Romeo didn't respond to our mails. I think a there is a greater chance if a customer contacts them.
