### ISSUE TITLE
Setup server

### ISSUE THREAD

**Issue by wvengen** [foodcoops/foodcoops.net#8]
When #5 is becoming clear and we'll have a date when we'd be able to move over, it is time to setup a cloud server. See [this message](http://foodsoft.51229.x6.nabble.com/Technical-steps-tp1416p1426.html) for details:
> ```
>   PROVIDER   RAM  CPU HD    BW    EUR/m ECO
>   Leaseweb   2GB  2   60GB   6TB  10    
>   Leaseweb   4GB  4   80GB   8TB  18    
>   Greenhost  2GB  1   20GB   2TB  29     y
>   Greenhost  4GB  2   50GB   4TB  49     y
>   Hetzner    2GB  2   50GB   5TB   8    
>   Hetzner    4GB  2  100GB   8TB  14    
>   Netcup     2GB  2   40GB  25TB   4     y
>   Netcup     4GB  4   80GB  25TB   5     y
>   Netcup     8GB  6  160GB  25TB   9     y 
> ```
>  Netcup looks like a good choice, with the current options I'd go for the 4GB RAM option and see if we can manage with that.

Order it, check if it's allright. Setup docker and check it's working smoothly. Add SSH keys of operations team. Come up with a becoming-root solution and get agreement on the mailing-list (ssh as root, sudo, su, passwordless su/sudo or not, ...).

**Comment by JuliusR** [comment]
After we agree in #10 about the name and payment option, I can care about this.

**Comment by JuliusR** [comment]
Due to missing experience I would follow your suggestion with 4 GB RAM, but upgrade as soon as we think it might be useful. I think we should not accept any inconveniences just for saving 4 Euro per month.

Quoting [terms and conditions of netcup](https://www.netcup.eu/bestellen/agb.php), that is possible also if we choose the [contract for 12 months](https://www.netcup.eu/bestellen/produkt.php?produkt=1754):

> 7. During the contractual term, the customer may opt to switch to a package offering a greater level of performance (upgrade) at any time. netcup can provide customers with details of any fees charged for such an upgrade. Once the upgrade is complete, a new contract ? potentially with a new minimum term ? commences on the basis of the service specification and T&Cs applicable at the time of the upgrade. In the event of an upgrade to a higher-value package, any unused customer payments for the old package will be reimbursed.

**Comment by JuliusR** [comment]
> Come up with a becoming-root solution and get agreement on the mailing-list (ssh as root, sudo, su, passwordless su/sudo or not, ...).

I can propose something concerning that point to get the discussion started, but where? Is the now-public nabble list fine for that?

**Comment by wvengen** [comment]
We could ask for ssh keys on private emails or on the private mailing-list (signed, of course). How we manage them, handle root access, etc. may be discussed publically (in my humble opinion).

**Comment by wvengen** [comment]
I think we're there with the server! :)
